name: FastAPI Docker CI/CD - Dev V1

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}

    env:
      REGISTRY: ghcr.io
      REPO: ${{ github.repository }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set IMAGE_NAME
        run: echo "IMAGE_NAME=${{ env.REGISTRY }}/${{ env.REPO }}:latest" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME .
          docker tag $IMAGE_NAME ${{ env.REGISTRY }}/${{ env.REPO }}:${{ github.sha }}

      - name: Push to GHCR
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.REPO }}:${{ github.sha }}
          docker push $IMAGE_NAME


      - name: Prepare SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: SSH to server and deploy Docker container
        env:
          IMAGE_NAME: ${{ vars.IMAGE_NAME }}
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
          BE_SERVER_IP: ${{ secrets.BE_SERVER_IP }}
          BE_SERVER_PORT: ${{ secrets.BE_SERVER_PORT }}
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_IP }} << EOF
            echo "$GHCR_TOKEN" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
            
            docker stop moa-ai || true
            docker rm -f moa-ai || true
            docker system prune -af
            
            docker pull $IMAGE_NAME
            
            docker run -d --name moa-ai \
              --restart unless-stopped \
              -p 8000:8000 \
              -e BE_SERVER_IP="$BE_SERVER_IP" \
              -e BE_SERVER_PORT="$BE_SERVER_PORT" \
              -e ENVIRONMENT="$ENVIRONMENT" \
              -e HF_TOKEN="$HF_TOKEN" \
              -e OPENAI_API_KEY="$OPENAI_API_KEY" \
              $IMAGE_NAME
          EOF